### ISSUE TITLE
Gender on the DogClass

### ISSUE THREAD

**Issue by M-a-c** [shirley1997/lucysfamily#1]
@shirley1997 
https://github.com/shirley1997/lucysfamily/blob/master/javadog/Dog.java#L5
Hey I wanted to say that you might want to put Gender onto the animal class since it would be used by more than just dog if you add more animals.

**Comment by shirley1997** [comment]
uhhhh you are right but firstly can we just concentrate on dog?lol i tried to write " enum gender{MALE,FEMALE}" before "public dog",but seems like it dosen't work??and what datatype should i choose for gender?string??how i can let computer choose what gender it is?

**Comment by M-a-c** [comment]
An enum would work fine
``` java
class Untitled {
	
	enum Gender {MALE, FEMALE}
	public static void main(String[] args) {
		Gender myGender = Gender.MALE;
		Gender yourGender = Gender.FEMALE;
		
		if(myGender == yourGender) {
			System.out.println("something is wrong");
		}
		else {
			System.out.print("these genders are different");
			System.out.print(myGender);
			System.out.print(yourGender);
		}
	}
}
```

**Comment by shirley1997** [comment]
wowwwwwwwwwwwww thank you so much!!!!now i'll try to combine it to my code!!

**Comment by M-a-c** [comment]
``` java
// General form of an enum
enum TypeName { ITEM, ITEM2, ITEM3...}

// Declaring 
TypeName VariableName = TypeName.ITEM_NUMBER;
```
